const slides = [
 {k:'OPENING',t:'NotebookLM活用術',lead:'自分の資料を根拠にして、読む・聞く・考える時間を短くする60分。',type:'open',items:[['今日できること','資料を集め、質問し、成果物に変える一連の流れを体験します。','🎯'],['大切な前提','NotebookLMは「入れた資料」をもとに答えるAIです。','📚'],['ゴール','明日から使える、自分用の調査ノートを1冊作る。','🚀']]},
 {k:'01 · 全体像',t:'NotebookLMは「資料に聞く」AI',lead:'Web全体ではなく、あなたが指定したソースを読んで回答するのが特徴です。',type:'flow',steps:[['資料を集める','PDF・Web・Driveなど'],['ノートに入れる','読む範囲を決める'],['質問・生成する','根拠付きで使う']]},
 {k:'01 · 比較',t:'GeminiとNotebookLMの使い分け',lead:'目的ではなく「答えの根拠」がどこにあるかで選びます。',type:'compare',items:[['Gemini','発想・下書き・幅広い検索\n「何から考える？」','💡'],['NotebookLM','自分の資料の理解・整理\n「この資料には何とある？」','📖']]},
 {k:'01 · 基礎',t:'NotebookLMの基本画面',lead:'操作はシンプルです。左から「ソース」、中央で「会話」、右で「成果物」。',type:'open',items:[['ソース','資料を追加し、必要ならON/OFFを切り替えます。','①'],['チャット','資料の内容を質問。引用をたどって確かめます。','②'],['Studio','音声解説・要約・FAQなどに変換します。','③']]},
 {k:'02 · ハンズオン',t:'ハンズオンのシナリオ',lead:'「勉強会の企画担当者」として、共有資料から参加者向けの説明を作ります。',type:'flow',steps:[['準備','資料3点を用意'],['理解','質問で要点を確認'],['転用','FAQと説明原稿を作成']]},
 {k:'02 · Step 1',t:'ノートブックを作る',lead:'最初にテーマを1つに絞ります。複数テーマを混ぜないことが、答えの質を上げます。',type:'open',items:[['操作','NotebookLMで「新しいノートブック」を選ぶ。','🗂️'],['名前','例：夏の勉強会｜参加者案内','✏️'],['確認','ノート名だけでなく、目的を自分で言える状態にする。','✓']]},
 {k:'02 · Step 2',t:'ソースを追加する',lead:'答えてほしい範囲の資料だけを入れます。まずは少数・高品質から始めます。',type:'open',items:[['入れられるもの','PDF、Googleドキュメント、Webページ、YouTubeなど。','📎'],['おすすめ','企画書・過去の案内・Q&Aの3点から開始。','🧩'],['注意','公開前の機密情報や個人情報は、組織ルールを確認。','⚠️']]},
 {k:'02 · Step 3',t:'まず「地図」を作る質問',lead:'いきなり文章を作らず、資料全体の構造と不足を確かめます。',type:'check',checks:['この資料の目的を3行で説明して','参加者が知るべきことを箇条書きにして','資料ごとの役割と重複を示して','根拠となる資料名も添えて']},
 {k:'02 · Step 4',t:'答えは引用から確かめる',lead:'便利な回答ほど、根拠を開いて確認する習慣をつけましょう。',type:'flow',steps:[['回答を読む','結論をつかむ'],['引用を開く','元資料の箇所へ戻る'],['判断する','自分の文として採用・修正']]},
 {k:'02 · Step 5',t:'質問を具体化して精度を上げる',lead:'「何を」「誰向けに」「どの形式で」を一度に伝えると、使える答えになります。',type:'open',items:[['弱い質問','この資料を要約して','△'],['良い質問','初参加の社会人向けに、申込前に知るべき点を5項目で。資料の根拠も示して。','◎'],['コツ','制約（文字数・対象・形式）を足す。','🔧']]},
 {k:'02 · Step 6',t:'Studioで成果物のたたきを作る',lead:'理解した内容を、読む・聞く・配る形へ変換します。最終確認は必ず人が行います。',type:'open',items:[['よく使う形','概要、FAQ、学習ガイド、音声解説。','🧰'],['使いどころ','移動中の復習、会議前の把握、初稿づくり。','🎧'],['最後の確認','言い回し・数字・固有名詞は元資料と照合。','🔍']]},
 {k:'03 · 実務活用',t:'3つの仕事シーンに当てはめる',lead:'情報を探す作業から、根拠を持って説明する作業へ。',type:'open',items:[['会議前','資料一式から論点と決定事項を拾う。','🗓️'],['引き継ぎ','過去資料からFAQと注意点を作る。','🤝'],['学習','複数資料の比較表と確認問題を作る。','📘']]},
 {k:'03 · 注意',t:'安全に使うための4つの確認',lead:'AIの出力をそのまま社外へ出さない。判断と責任は使う人に残ります。',type:'check',checks:['ソースに含めてよい情報か確認する','回答の引用を開いて原文を確認する','最新性が必要な情報は別途確認する','生成物を配る前に人が最終レビューする']},
 {k:'CLOSING',t:'明日からの最初の一歩',lead:'1つの業務テーマ、3つの資料、3つの質問から始めましょう。',type:'open',items:[['1. 集める','今日扱った資料を1つのノートに。','📥'],['2. 聞く','目的・要点・不足を質問する。','💬'],['3. 確かめる','引用を開き、自分の言葉で使う。','✅']]}
];
const deck=document.querySelector('#deck'),toc=document.querySelector('#toc'),counter=document.querySelector('#counter');let current=0;
function esc(v){return String(v).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
function boxes(items){return `<div class="grid three">${items.map(([h,p,i],n)=>`<article class="box ${n===1?'accent':''}"><span class="box__tab">POINT ${n+1}</span><span class="box__icon">${i}</span><h3>${esc(h)}</h3><p>${esc(p).replace(/\n/g,'<br>')}</p></article>`).join('')}</div>`}
function visual(s){if(s.type==='flow')return `<div class="flow">${s.steps.map((x,i)=>`<div class="flow__step"><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p></div>${i<s.steps.length-1?'<span class="flow__arrow">→</span>':''}`).join('')}</div>`;if(s.type==='compare')return `<div class="compare"><article class="box"><span class="box__tab">広く考える</span><span class="box__icon">${s.items[0][2]}</span><h3>${s.items[0][0]}</h3><p>${s.items[0][1].replace(/\n/g,'<br>')}</p></article><div class="compare__vs">目的で<br>選ぶ</div><article class="box accent"><span class="box__tab">資料で考える</span><span class="box__icon">${s.items[1][2]}</span><h3>${s.items[1][0]}</h3><p>${s.items[1][1].replace(/\n/g,'<br>')}</p></article></div>`;if(s.type==='check')return `<div class="checklist">${s.checks.map(x=>`<div class="check">${esc(x)}</div>`).join('')}</div><div class="tip">回答を受け取ったら、引用を1つ開いて確認する。</div>`;return boxes(s.items)}
function render(){deck.innerHTML=slides.map((s,i)=>`<section class="slide ${i===current?'active':''}" id="slide-${i}"><p class="slide__kicker">${s.k}</p><h2>${s.t}</h2><div class="rule"></div><p class="lead">${s.lead}</p>${visual(s)}<span class="page">${String(i+1).padStart(2,'0')} / ${slides.length}</span></section>`).join('');toc.innerHTML=slides.map((s,i)=>`<button class="${i===current?'active':''}" data-slide="${i}">${String(i+1).padStart(2,'0')}　${s.t}</button>`).join('');counter.textContent=`${current+1} / ${slides.length}`;toc.querySelectorAll('button').forEach(b=>b.onclick=()=>{current=Number(b.dataset.slide);render()});}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='print')return window.print();current=(current+(a==='next'?1:-1)+slides.length)%slides.length;render();}));document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){current=(current+1)%slides.length;render()}if(e.key==='ArrowLeft'){current=(current-1+slides.length)%slides.length;render()}});render();
