const slides = [
  {title:'Google AI Studioでつくる\nはじめてのWebアプリ',kicker:'DAY 5｜ノーコード・Webアプリ構築',icon:'i-compass',cover:true,body:`<p class="cover__lead">プログラミング経験がなくても、言葉で伝えながら小さなアプリをつくる。今日は「動くもの」を安全に、仕事に引き寄せて体験します。</p><div class="cover__badge"><svg class="icon"><use href="#i-spark"/></svg>ゴール：自分のアイデアを、試せる形にする</div>`},
  {title:'80分の道のり',kicker:'今日の全体像',icon:'i-compass',body:`<div class="timeline"><div class="timeline__item"><b>3分</b>オープニング</div><div class="timeline__item"><b>4+5分</b>安全・プロンプト</div><div class="timeline__item"><b>5+4+4分</b>Build・モデル・保存</div><div class="timeline__item"><b>20分</b>初級ハンズオン</div><div class="timeline__item"><b>10+25分</b>休憩・中級ハンズオン<br><span class="small">最後の5分は保存・共有・フォロー</span></div></div><div class="notice" style="margin-top:clamp(25px,4vw,55px)"><svg class="icon"><use href="#i-bulb"/></svg><div><strong>今日の進め方：</strong>小さく作る → 動きを見る → 一言ずつ直す。正解を当てる場ではなく、AIとの対話を試す場です。</div></div>`},
  {title:'Google AI Studioとは',kicker:'試作のための、AIとの作業場',icon:'i-code',body:`<div class="flow"><div class="flow__step"><svg class="icon"><use href="#i-bulb"/></svg>思いつき</div><div class="flow__arrow">→</div><div class="flow__step"><svg class="icon"><use href="#i-spark"/></svg>言葉で依頼</div><div class="flow__arrow">→</div><div class="flow__step"><svg class="icon"><use href="#i-code"/></svg>Buildで形に</div><div class="flow__arrow">→</div><div class="flow__step"><svg class="icon"><use href="#i-check"/></svg>試して改善</div></div><div class="card-grid cols-2" style="margin-top:30px"><article class="card"><span class="card__tab">できること</span><svg class="icon"><use href="#i-spark"/></svg><h3>試作をすばやく形にする</h3><p>プロンプト、画面、コードのたたき台をつくり、ブラウザで動きを確かめます。</p></article><article class="card card--teal"><span class="card__tab">心構え</span><svg class="icon"><use href="#i-check"/></svg><h3>最初から完成を目指さない</h3><p>小さな動作確認から始め、会話しながら育てます。</p></article></div>`},
  {title:'安全に使うための前提',kicker:'入力前に、境界線を決める',icon:'i-shield',body:`<div class="card-grid cols-2"><article class="card"><span class="card__tab">入力しない</span><svg class="icon"><use href="#i-shield"/></svg><h3>実データ・機密・個人情報</h3><ul class="list-check"><li>顧客名、メールアドレス、社内の未公開情報</li><li>パスワード、APIキー、ログイン情報</li><li>本人が特定できる相談内容</li></ul></article><article class="card card--teal"><span class="card__tab">今日の安全策</span><svg class="icon"><use href="#i-check"/></svg><h3>架空データで試す</h3><ul class="list-check"><li>ニュース検索は公開情報のみ</li><li>仕事は「営業」「人事」など抽象化して入力</li><li>外部ツール連携は今日は使わない</li></ul></article></div><div class="notice" style="margin-top:25px"><svg class="icon"><use href="#i-bulb"/></svg><div><strong>迷ったら入れない。</strong>便利さより、情報を守る判断を優先します。</div></div>`},
  {title:'伝わるプロンプトは、4つで考える',kicker:'ミニ演習｜「何を、誰のために、どんな形で」',icon:'i-bulb',body:`<div class="card-grid cols-2"><article class="card"><span class="card__tab">1・2</span><h3>目的と利用者</h3><p>何を解決したいか。誰が使うか。</p></article><article class="card card--teal"><span class="card__tab">3・4</span><h3>入力と出力</h3><p>何を入力し、どの画面・形式で返すか。</p></article></div><div class="prompt-box" style="margin-top:22px"><strong>悪い例：</strong> クイズを作って。<br><strong>良い例：</strong> 営業職向けの「あるある診断」クイズを作って。5つの質問に答えると、診断結果と一言アドバイスを表示して。</div><p class="small" style="margin-top:13px">まずは目的を1つ、出力を1つ足すだけで、生成結果の方向がそろいます。</p>`},
  {title:'バイブコーディング：言葉で作り、動きで確かめる',kicker:'Build機能の実演デモ',icon:'i-code',body:`<div class="flow"><div class="flow__step">やりたいことを<br>言葉にする</div><div class="flow__arrow">→</div><div class="flow__step">AIがアプリの<br>たたき台をつくる</div><div class="flow__arrow">→</div><div class="flow__step">画面を触って<br>動きを見る</div><div class="flow__arrow">→</div><div class="flow__step">直したいことを<br>追加で伝える</div></div><div class="notice" style="margin-top:34px"><svg class="icon"><use href="#i-check"/></svg><div><strong>大切なのは「生成されたから正しい」ではないこと。</strong>画面、文言、意図しない動きを必ず自分で確認します。</div></div>`},
  {title:'モデル選びと、止まったときの見方',kicker:'最初は Gemini 3.6 Flash から',icon:'i-spark',body:`<div class="card-grid cols-3"><article class="card"><span class="card__tab">出発点</span><svg class="icon"><use href="#i-spark"/></svg><h3>Gemini 3.6 Flash</h3><p>まずは軽快に試作。小さなアプリづくりから始めます。</p></article><article class="card card--teal"><span class="card__tab">困ったら</span><svg class="icon"><use href="#i-search"/></svg><h3>条件を確認</h3><p>選んだモデル、公開設定、利用上限、エラーの本文を順に見ます。</p></article><article class="card"><span class="card__tab">403 のとき</span><svg class="icon"><use href="#i-shield"/></svg><h3>権限の合図</h3><p>操作を繰り返さず、アカウント・設定・対象の権限を確認します。</p></article></div>`},
  {title:'保存・共有は「小さく」',kicker:'ハンズオンへの準備',icon:'i-save',body:`<div class="two-panel"><div><div class="steps"><div class="step"><strong>保存：</strong>作った時点で名前を付ける</div><div class="step"><strong>共有：</strong>見せてよい内容だけを対象にする</div><div class="step"><strong>記録：</strong>使ったプロンプトも残す</div></div></div><div class="notice"><svg class="icon"><use href="#i-share"/></svg><div><strong>公開前の確認：</strong>画面に実データ、キー、社内情報が表示されていないかを見直してから共有します。</div></div></div>`},
  {title:'初級ハンズオン｜あるある診断クイズ',kicker:'20分｜1プロンプトで、まず動かす',icon:'i-bulb',body:`<div class="card-grid cols-2"><article class="card"><span class="card__tab">ねらい</span><svg class="icon"><use href="#i-spark"/></svg><h3>「秒で完成」を体験する</h3><p>自分の仕事に寄せた小さなアプリで、成功体験をつくります。</p></article><article class="card card--teal"><span class="card__tab">題材</span><svg class="icon"><use href="#i-compass"/></svg><h3>自分の業界・仕事のあるある</h3><p>業界を明かしたくないときは、歴史クイズなど好きなテーマで構いません。</p></article></div><div class="flow" style="margin-top:30px"><div class="flow__step">テーマを決める</div><div class="flow__arrow">→</div><div class="flow__step">プロンプトを送る</div><div class="flow__arrow">→</div><div class="flow__step">5問を答えてみる</div></div>`},
  {title:'初級｜この1文から始める',kicker:'自分の言葉に置き換えて送信',icon:'i-spark',body:`<div class="prompt-box">「<strong>【自分の業界・仕事】</strong>あるある診断クイズを作って。<strong>5つの質問</strong>に答えると<strong>診断結果</strong>が出るようにして。」</div><div class="card-grid cols-3" style="margin-top:25px"><article class="card"><span class="card__tab">1</span><h3>【 】を置換</h3><p>例：営業職、保育、接客、経理</p></article><article class="card card--teal"><span class="card__tab">2</span><h3>Buildで生成</h3><p>生成された画面を開きます。</p></article><article class="card"><span class="card__tab">3</span><h3>最後まで回答</h3><p>質問と診断結果を確認します。</p></article></div>`},
  {title:'初級｜動いたら、ひとつだけ育てる',kicker:'確認 → 小さな改善',icon:'i-check',body:`<div class="card-grid cols-2"><article class="card"><span class="card__tab">確認</span><svg class="icon"><use href="#i-check"/></svg><h3>見るポイント</h3><ul class="list-check"><li>5つの質問が表示されるか</li><li>最後に診断結果が出るか</li><li>自分にとって分かる表現か</li></ul></article><article class="card card--teal"><span class="card__tab">改善例</span><svg class="icon"><use href="#i-bulb"/></svg><h3>一度に一つだけ頼む</h3><p>「結果に、明日から試せる一言アドバイスを追加して」</p></article></div><div class="notice" style="margin-top:25px"><svg class="icon"><use href="#i-compass"/></svg><div><strong>フォールバック：</strong>テーマが思いつかない・業界を言いたくない場合は「戦国武将診断」「日本史年号クイズ」などに切り替えます。</div></div>`},
  {title:'休憩｜10分',kicker:'ここまでの成果を保存',icon:'i-save',body:`<div class="flow"><div class="flow__step">いったん保存</div><div class="flow__arrow">→</div><div class="flow__step">画面を閉じて休む</div><div class="flow__arrow">→</div><div class="flow__step">戻ったら中級へ</div></div><p class="cover__lead" style="text-align:center;margin:clamp(42px,7vw,100px) auto 0">次は、AIと対話しながら<br>ニュース検索ツールを育てます。</p>`},
  {title:'中級ハンズオン｜ニュース検索＆要約ツール',kicker:'25分｜最初の依頼 + 改善4つ',icon:'i-search',body:`<div class="card-grid cols-2"><article class="card"><span class="card__tab">ねらい</span><svg class="icon"><use href="#i-spark"/></svg><h3>会話でアプリを育てる</h3><p>一度で完璧にせず、要望を足してアプリを変化させます。</p></article><article class="card card--teal"><span class="card__tab">約束</span><svg class="icon"><use href="#i-shield"/></svg><h3>公開情報だけで試す</h3><p>実データや外部サービスの連携は、今日は扱いません。</p></article></div><div class="prompt-box" style="margin-top:22px">「キーワードを入力すると最新ニュースを<strong>5件</strong>検索し、タイトル・要約（<strong>100字</strong>）・URLを表示するツールを作って。」</div>`},
  {title:'中級｜改善 1・2',kicker:'「一覧」から「自分ごと」へ',icon:'i-bulb',body:`<div class="steps"><div class="step"><strong>改善1：</strong>ニュースの詳細ページを作って。一覧に詳細ボタンを追加。ボタンを押したら、別ページでそのニュースの詳細情報を検索して表示して。</div><div class="step"><strong>改善2：</strong>詳細ページの中に「このニュースが自分にとってどんな価値があるか」をAI解説できるようにして。私の仕事は「●●」です。</div></div><div class="notice" style="margin-top:20px"><svg class="icon"><use href="#i-shield"/></svg><div><strong>仕事は抽象的に入力。</strong>社名や顧客情報は書かず、「広報」「採用担当」などに置き換えます。</div></div>`},
  {title:'中級｜改善 3・4',kicker:'広げる → 見せ方を整える',icon:'i-spark',body:`<div class="steps"><div class="step"><strong>改善3：</strong>詳細ページに「関連ニュースを調べる」ボタンを追加して。検索ワードをAIが3種類つくって提案してくれるようにして。検索ワードをクリックしたら、新たなニュース結果を表示して。</div><div class="step"><strong>改善4：</strong>詳細ページを開いたら、そのニュースを表現するイメージ画像を自動生成して表示するようにして。</div></div><div class="flow" style="margin-top:24px"><div class="flow__step">記事を読む</div><div class="flow__arrow">→</div><div class="flow__step">関連語を選ぶ</div><div class="flow__arrow">→</div><div class="flow__step">次の発見へ</div></div>`},
  {title:'中級｜安全な範囲で試す',kicker:'外部連携は、今日は使わない',icon:'i-shield',body:`<div class="two-panel"><article class="card"><span class="card__tab">今日やること</span><svg class="icon"><use href="#i-check"/></svg><h3>公開ニュースで試作</h3><ul class="list-check"><li>キーワード検索</li><li>要約と詳細表示</li><li>職種に合わせた価値の解説</li></ul></article><article class="card card--teal"><span class="card__tab">今日見送ること</span><svg class="icon"><use href="#i-shield"/></svg><h3>実データ・OAuth連携</h3><ul class="list-check"><li>Google Sheets / Gmailの接続</li><li>ログイン権限を求める操作</li><li>未検証コードへの実データ入力</li></ul></article></div><p class="small" style="margin-top:17px">連携は便利ですが、権限・誤操作・情報漏えいのリスクを理解してから段階的に扱います。</p>`},
  {title:'保存・共有・次の一歩',kicker:'最後の5分｜成果を持ち帰る',icon:'i-share',body:`<div class="card-grid cols-3"><article class="card"><span class="card__tab">保存</span><svg class="icon"><use href="#i-save"/></svg><h3>アプリ名とプロンプト</h3><p>何を頼んだかも、一緒に残します。</p></article><article class="card card--teal"><span class="card__tab">共有</span><svg class="icon"><use href="#i-share"/></svg><h3>画面を見せ合う</h3><p>公開してよい内容だけで、学びを共有します。</p></article><article class="card"><span class="card__tab">次回</span><svg class="icon"><use href="#i-compass"/></svg><h3>小さく再挑戦</h3><p>仕事の「面倒」を一つ選び、試作から始めましょう。</p></article></div><div class="notice" style="margin-top:27px"><svg class="icon"><use href="#i-spark"/></svg><div><strong>今日の合言葉：</strong>小さく、安全に、AIと対話しながら育てる。</div></div>`}
];

const deck = document.querySelector('#deck');
const nav = document.querySelector('#rail-nav');
const counter = document.querySelector('#counter');
let current = 0;
const icon = id => `<svg class="icon" aria-hidden="true"><use href="#${id}"/></svg>`;
deck.innerHTML = slides.map((s,i)=>`<article class="slide ${i===0?'is-active':''}" id="slide-${i+1}"><div class="slide__frame ${s.cover?'cover':''}">${s.cover?`${icon(s.icon).replace('class="icon"','class="cover-icon"')}`:''}<header class="slide__head"><div><p class="kicker">${s.kicker}</p><${s.cover?'h1':'h2'}>${s.title.replace(/\n/g,'<br>')}</${s.cover?'h1':'h2'}></div>${s.cover?'':icon(s.icon)}</header><div class="slide__body">${s.body}</div><footer class="slide__footer">AIやろうぜ in Fukuoka、AI Summer school 2026</footer><span class="page-no">${String(i+1).padStart(2,'0')}</span></div></article>`).join('');
nav.innerHTML = slides.map((s,i)=>`<a href="#slide-${i+1}" data-index="${i}"><span>${String(i+1).padStart(2,'0')}</span>${s.title.replace(/\n/g,' ')}</a>`).join('');
function go(index){current=(index+slides.length)%slides.length;document.querySelectorAll('.slide').forEach((el,i)=>el.classList.toggle('is-active',i===current));document.querySelectorAll('.rail__nav a').forEach((el,i)=>el.classList.toggle('is-active',i===current));counter.textContent=`${current+1} / ${slides.length}`;document.querySelector(`#slide-${current+1}`).scrollIntoView({behavior:'smooth',block:'start'});}
nav.addEventListener('click',e=>{const a=e.target.closest('a');if(a){e.preventDefault();go(Number(a.dataset.index));}});
document.querySelector('#prev').addEventListener('click',()=>go(current-1));document.querySelector('#next').addEventListener('click',()=>go(current+1));document.querySelector('#print-button').addEventListener('click',()=>window.print());
document.addEventListener('keydown',e=>{if(['ArrowRight','PageDown'].includes(e.key))go(current+1);if(['ArrowLeft','PageUp'].includes(e.key))go(current-1);});go(0);
